"""
Generate the engine seed data SQL migration from CSV files and day_types.sql.
Outputs: supabase/migrations/20260240000000_engine_seed_data.sql
"""
import csv
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT = os.path.join(ROOT, "supabase", "migrations", "20260240000000_engine_seed_data.sql")


def escape_sql(val: str) -> str:
    """Escape single quotes for SQL."""
    return val.replace("'", "''")


def sql_val(val: str | None) -> str:
    """Convert a CSV value to a SQL literal."""
    if val is None or val.strip() == "":
        return "NULL"
    return f"'{escape_sql(val.strip())}'"


def jsonb_val(val: str | None) -> str:
    """Convert a CSV JSON value to a SQL jsonb literal."""
    if val is None or val.strip() == "":
        return "NULL"
    return f"'{escape_sql(val.strip())}'::jsonb"


def numeric_val(val: str | None) -> str:
    if val is None or val.strip() == "":
        return "NULL"
    return val.strip()


def int_val(val: str | None) -> str:
    if val is None or val.strip() == "":
        return "NULL"
    return val.strip()


def generate():
    lines = []
    lines.append("-- Engine seed data: day types, 720 workouts, program mappings")
    lines.append("-- Auto-generated by scripts/generate_engine_seed.py\n")

    # 1. Day types (read from day_types.sql)
    lines.append("-- ==========================================")
    lines.append("-- 1. Engine day types (22 rows)")
    lines.append("-- ==========================================")
    dt_path = os.path.join(ROOT, "day_types.sql")
    with open(dt_path, "r") as f:
        # Rewrite to target engine_day_types table
        content = f.read()
        content = content.replace(
            'INSERT INTO "public"."day_types"',
            'INSERT INTO "public"."engine_day_types"'
        )
        lines.append(content)
    lines.append("")

    # 2. Engine workouts (720 rows from 720.csv)
    lines.append("-- ==========================================")
    lines.append("-- 2. Engine workouts (720 rows)")
    lines.append("-- ==========================================")

    csv_path = os.path.join(ROOT, "720.csv")
    with open(csv_path, "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        values = []
        for row in reader:
            vals = (
                f"  ({sql_val(row['id'])}, "
                f"{sql_val(row['program_type'])}, "
                f"{int_val(row.get('day_number'))}, "
                f"{sql_val(row['day_type'])}, "
                f"{int_val(row.get('phase'))}, "
                f"{int_val(row.get('block_count'))}, "
                f"{int_val(row.get('set_rest_seconds'))}, "
                f"{jsonb_val(row.get('block_1_params'))}, "
                f"{jsonb_val(row.get('block_2_params'))}, "
                f"{jsonb_val(row.get('block_3_params'))}, "
                f"{jsonb_val(row.get('block_4_params'))}, "
                f"{int_val(row.get('total_duration_minutes'))}, "
                f"{numeric_val(row.get('base_intensity_percent'))}, "
                f"{int_val(row.get('month'))}, "
                f"{numeric_val(row.get('avg_work_rest_ratio'))}, "
                f"{sql_val(row.get('created_at'))}, "
                f"{sql_val(row.get('updated_at'))})"
            )
            values.append(vals)

    lines.append(
        "INSERT INTO engine_workouts "
        "(id, program_type, day_number, day_type, phase, block_count, "
        "set_rest_seconds, block_1_params, block_2_params, block_3_params, "
        "block_4_params, total_duration_minutes, base_intensity_percent, "
        "month, avg_work_rest_ratio, created_at, updated_at) VALUES"
    )
    lines.append(",\n".join(values) + ";")
    lines.append("")

    # 3. Engine program mapping (2582+ rows from 2582.csv)
    lines.append("-- ==========================================")
    lines.append("-- 3. Engine program mapping")
    lines.append("-- ==========================================")

    csv_path = os.path.join(ROOT, "2582.csv")
    with open(csv_path, "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        values = []
        for row in reader:
            vals = (
                f"  ({int_val(row.get('id'))}, "
                f"{sql_val(row.get('engine_program_id'))}, "
                f"{int_val(row.get('engine_workout_day_number'))}, "
                f"{int_val(row.get('program_sequence_order'))}, "
                f"{int_val(row.get('week_number'))}, "
                f"{sql_val(row.get('notes'))}, "
                f"{sql_val(row.get('created_at'))})"
            )
            values.append(vals)

    lines.append(
        "INSERT INTO engine_program_mapping "
        "(id, engine_program_id, engine_workout_day_number, "
        "program_sequence_order, week_number, notes, created_at) VALUES"
    )
    lines.append(",\n".join(values) + ";")

    # Reset serial sequence for engine_program_mapping
    lines.append("")
    lines.append("-- Reset serial sequence")
    lines.append(
        "SELECT setval('engine_program_mapping_id_seq', "
        "(SELECT MAX(id) FROM engine_program_mapping));"
    )

    with open(OUTPUT, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Generated {OUTPUT}")
    print(f"  Day types: 22 rows")
    print(f"  Workouts: {len(values)} rows (from mapping, workouts counted above)")


if __name__ == "__main__":
    generate()
